### PR TITLE
Add requirement pinnings

### PR DESCRIPTION
**Pull request by pumazi**
This gives us the ability to pin to specific versions. See cnx-press as an
example of why this is good. The most direct benefit of this is when used
in relation to pyup.io. Our tests are run when a new dependency is released,
this is important, because we are then able to see breakage prior to deployment.

### CODE REVIEW

**Comment by pumazi** [comment]
This was from a cherry-picked commit. It was missing several things, but I thought it was mostly accurate. I stuck with it because I figured pyup would do the remaining heavy lifting. So I'll redo it.

**Comment by pumazi** [comment]
Actually... Maybe we leave it as is to later exercise the work that will go into openstax/cnx#564

**Comment by karenc** [comment]
> Actually... Maybe we leave it as is to later exercise the work that will go into [openstax/cnx#564](https://github.com/openstax/cnx/issues/564). @karenc thoughts?

@pumazi Yeah that's fine.  I actually thought that would be implemented first :stuck_out_tongue: 

I guess we're not going to use it in cnx-deploy yet so it doesn't need to match completely.

**Comment by pumazi** [comment]
> I actually thought that would be implemented first 😛

🤔 Yeah, me too. But somebody numbered these in such a way that this one comes first. 😕

**Comment by pumazi** [comment]
Let's put a brief hold on this and pull openstax/cnx#564 forward to see what comes of it.

**Comment by pumazi** [comment]
Closing, because I'm not exactly happen with the results. They aren't systematically produced, so that's going to probably bite us later.

**Pull request closed without merging**
